- src/components/Form/Inputs/SelectField.tsx
- src/components/Form/Inputs/SelectMultipleField.tsx
- src/components/Table/Widget/Field/ColorWidget/ColorWidget.tsx
- src/components/Table/Widget/Widget.tsx
- added props resetOnClose in multiselect and select
- added infoselection in printColor from widget
- change loading in select
> Fb fix validate number picker

- package.json
- src/components/Form/Inputs/DateTimePicker.tsx
- src/components/Form/Inputs/NumericField.tsx
- src/components/Form/Inputs/SelectField.tsx
- src/components/Form/Inputs/SelectMultipleField.tsx
- src/components/Table/Widget/Field/ColorWidget/ColorWidget.tsx
- src/components/Table/Widget/Widget.tsx
- src/index.tsx
> feat: Update Number Input

- src/components/ColorPicker/style.tsx
- src/components/Form/Inputs/NumericField.tsx
- src/components/TabsPanel/style.tsx
- Clear console.log,
-  Added border to colorpicker
> duafeat: clear console.log, added border to colorpicker

- src/components/Form/Inputs/SelectMultipleField.tsx
> feat: fix multiselect selection

- src/components/Form/Inputs/DateTimePicker.tsx
- src/components/Form/Inputs/FormFieldContainer.tsx
DateTimePicker value requirend with not fieldstate
> feat: fix dateTimePicker value and not fildstate required.

- src/components/Form/Inputs/SelectField.tsx
- src/components/Form/Inputs/SelectMultipleField.tsx
- Migrate multiselect to hooks
-  Added options clear to select and  multiselect
> feat: Migrate multiselect to hooks

- src/components/Form/Inputs/TextAreaField.tsx
> feat: Add props rows to Text-Area

- src/components/Form/Inputs/SelectMultipleField.tsx
- Add prop isLoading in multiselect
> feat: add prop isLoading in multiselect

- src/components/Form/Inputs/DateTimePicker.tsx
- src/components/Form/Inputs/style.tsx
hot fix datepicker include Portal
> Fb fix datepicker

- src/components/Form/Inputs/DateTimePicker.tsx
- src/components/Form/Inputs/style.tsx
Arrows overlapping month label on the date selector in Firefox
> feat: fix Arrows overlapping month label on the date selector in Firefox

- package.json
- src/components/Card/VCardPanel.tsx
- src/components/Dialog/VDraggableDialog.tsx
- src/components/Dialog/index.tsx
- src/components/Dialog/style.css
- src/components/index.ts
- yarn.lock
it is incluye draggable dialog
> it is incluye draggable dialog.

- src/components/Dialog/VDraggableDialog.tsx
fix add overFlowY in draggableDialog
> feat: fix overFlowY in draggableDialog.

- src/components/Dialog/VDraggableDialog.tsx
- src/components/Dialog/style.css
- src/components/Dialog/styled.tsx
> feat: style in vDraggableDialog with styled-component

- src/components/Form/Inputs/DateTimePicker.tsx
fix DateTimePicker on parse date
> feat: fix DateTimePicker on parse date

- src/components/Dialog/VDraggableDialog.tsx
- src/components/Dialog/styled.tsx
hotfix in dimension of the VDraggableDialog
@gsi-rafa
> hotfix in dimension of the VDraggableDialog

- package.json
- src/components/Dialog/VDraggableDialog.tsx
- src/components/Dialog/styled.tsx
- yarn.lock
hotfix generate an identifier for each vdraggabledialog
> hotfix generate an identifier for each vdraggabledialog

- src/components/Dialog/VDraggableDialog.tsx
hotfix remove overflow-y in VDraggableDialog
> hotfix remove overflow-y in VDraggableDialog

- src/components/Dialog/styled.tsx
hotfix include cursor move in VDraggableDialog
@gsi-rafa
> hotfix include cursor move in VDraggableDialog

- src/components/Dialog/VDraggableDialog.tsx
hotfix 
1- include unique id in each render in VDraggableDialog
2- refactorize recalculate zIndex in each render
> Fb fix draggable unique id render

- src/components/Dialog/VDraggableDialog.tsx
hotfix include portal in VDraggableDialog
@gsi-rafa
> hotfix include portal in VDraggableDialog

- src/components/Dialog/VDraggableDialog.tsx
> fix render dialog on dialog

- src/components/Dialog/VDraggableDialog.tsx
nclude classname in draggableDialog
> hotfix include classname in draggableDialog

- src/components/Dialog/VDraggableDialog.tsx
hotfix include "gsi-" in class name of VDraggabledialog
> hotfix include "gsi-" in class name of VDraggabledialog

- src/components/Dialog/VDraggableDialog.tsx
optimize the zIndex in VDraggableDialog
> hotfix optimize the zIndex in VDraggableDialog

- src/components/Scroll/CarouselMultiple/VCarouselMultiple.tsx
- src/components/Scroll/CarouselMultiple/components/Item.tsx
- src/components/Scroll/CarouselMultiple/components/SlideButton.tsx
- src/components/Scroll/CarouselMultiple/components/UseSizeElement.tsx
- src/components/Scroll/CarouselMultiple/components/UseSliding.tsx
- src/components/Scroll/CarouselMultiple/context.tsx
- src/components/Scroll/CarouselMultiple/style.tsx
- src/components/TabsPanel/TabsPanel.tsx
- src/components/TabsPanel/style.tsx
- src/index.tsx
Create carousel scroll for tabs
> add responsive to tabs

- src/components/VOrgChart/VOrgChart.tsx
- src/components/VOrgChart/index.ts
- src/components/VOrgChart/styles.tsx
- src/components/VOrgChart/types.ts
Update VOrgChart to allow use React template components
> Update VOrgChart to allow use React template components

- src/components/VOrgChart/VOrgChart.tsx
- src/components/VOrgChart/types.ts
> Add onRender graph method

- src/components/CancellablePromise/cancellablePromise.ts
- src/components/CancellablePromise/index.ts
- src/components/CustomHooks/index.ts
- src/components/CustomHooks/useCancellablePromises.ts
- src/components/CustomHooks/useClickPreventionOnDoubleClick.ts
- src/components/DragAndDropList/CustomDraggableItem.tsx
- src/components/DragAndDropList/CustomDraggableItemHelpButtons.tsx
- src/components/DragAndDropList/DNDItemWrapper.tsx
- src/components/DragAndDropList/DragAndDropList.tsx
- src/components/DragAndDropList/types.ts
- src/components/index.ts
- Created customs hooks for detect when is a single click and a doubleClick
- Created function to be able to cancel promises
> Feat - Added Double Click CallBack to Drag And Drop List

- .directory
- src/components/Scroll/CarouselMultiple/components/UseSizeElement.tsx
- src/components/Scroll/CarouselMultiple/components/UseSliding.tsx
- src/components/Scroll/CarouselMultiple/style.tsx
Fix Corrected eyelash and slider displays in different widths
> Fix: responsive tabs

- src/components/Form/Validators.ts
- Changed RequiredIf Validator to take a  function by parameter
> Feat - Modified RequiredIf validator

- src/components/SelectItems/SelectUnselectItems.tsx
- src/components/SelectItems/styles.tsx
- Changed the Select Unselect Component UI
- Improved styles in Select Unselect Items
- Added Custom Scroll Component
> Feat - Changed the Select Unselect Component UI

- src/components/Form/Validators.ts
- src/components/Scroll/CarouselMultiple/VCarouselMultiple.tsx
- src/components/SelectItems/SelectUnselectItems.tsx
- src/components/SelectItems/styles.tsx
Changed the selection and Unselect the item to be only with icons
> Fb: Change select unselect item

- src/components/Form/Validators.ts
- fixed lt validation
- fixed gt validation
- fixed exact validation
> Fixed: Some validations make app crash when the value is null

- src/components/Form/Inputs/SelectField.tsx
- src/components/Form/Inputs/SelectMultipleField.tsx
- updated styles from the divider
> Feat: Fixed Select not displaying the clear selection option when filtering

- src/components/Form/Validators.ts
fix: Error message spelling mistake
> fix: Error message spelling mistake

- src/components/Form/Inputs/MaskField.tsx
- src/components/Form/Inputs/style.tsx
- src/components/SelectionList/__snapshots__/SelectionList.test.tsx.snap
fix: Error in disabled property mask input field
> Fix: Error in disabled property mask input field

- src/components/DragAndDropList/DNDItemWrapper.tsx
- src/components/DragAndDropList/DNDList.tsx
- src/components/DragAndDropList/DragAndDropList.tsx
- src/components/DragAndDropList/style.tsx
- src/components/SelectionList/__snapshots__/SelectionList.test.tsx.snap
- src/index.tsx
- Improved refForward System to avoid crash
> Feat: Improved Code of DnD List

- src/components/Form/Inputs/NumericField.tsx
fix: Error in paste in numeric input
> fix: Error in paste in numeric input

- src/components/Form/Inputs/InputField.tsx
fix: Error in inputRef the inputField component
> fix: Error in inputRef the inputField component

- src/components/Form/Inputs/DateTimePicker.tsx
- src/index.tsx
> Fb fix date time picker

- src/components/Scroll/CarouselMultiple/VCarouselMultiple.tsx
- src/components/Scroll/CarouselMultiple/components/UseSizeElement.tsx
- src/components/Scroll/CarouselMultiple/components/UseSliding.tsx
> Fix: Tabs responsive

- src/components/Form/Inputs/SelectMultipleTags.tsx
- src/components/Scroll/CarouselMultiple/VCarouselMultiple.tsx
- src/components/Scroll/CarouselMultiple/components/UseSizeElement.tsx
- src/components/Scroll/CarouselMultiple/components/UseSliding.tsx
fix: include disabled vSelectMultipleTags, and tabs responsive
> Fix: include disabled vSelectMultipleTags, and tabs responsive

- src/components/Form/Inputs/DateTimePicker.tsx
- src/components/Form/Inputs/SelectMultipleTags.tsx
- Updated Select Multiple Tags to functional components and hooks
> Fixed: User clicks calendar icon should open up calendar

- src/components/Scroll/CarouselMultiple/VCarouselMultiple.tsx
- src/components/TabsPanel/TabsPanel.tsx
- src/components/TabsPanel/types.tsx
Fix: include isResponsive property in TabsPanel.
> fix: include isResponsive property in TabsPanel.

- src/components/Form/Inputs/VInputWIthSuggestions.tsx
- src/components/SelectItems/SelectUnselectItems.tsx
- Added Uppercase Format to search boxes
> Fixed- Fixed VInputWIthSuggestion popover height

- src/components/Form/Inputs/DateRange.tsx
- src/components/Form/Inputs/VInputWIthSuggestions.tsx
- src/components/Form/Inputs/style.tsx
- src/components/Form/index.ts
- src/components/SelectItems/SelectUnselectItems.tsx
- src/index.tsx
- Fixed some issues with the select unselect component
> Fixed- Created Date Range Input

- src/components/ColorPicker/ColorPicker.tsx
Fix: Include ColorPicker interaction click out side target.
> Fix: Include ColorPicker interaction click out side target.

- src/components/ColorPicker/ColorPicker.tsx
fix: Include ColorPicker prevent overflow
> fix: Include ColorPicker prevent overflow

- src/components/ColorPicker/types.tsx
fix: Add position auto in ColorPicker.
> fix: Add position auto in ColorPicker.

- src/components/Form/Inputs/VNumericFieldRounded.tsx
fix: Error when round To equals to 0
> fix: Error when roundTo equals to 0

- src/components/Card/VCardPanel.tsx
- src/components/Dialog/VDraggableModal/DraggableModalInner.tsx
- Add a parameter to change the style of VCardHeader component
> Fix - 299:  Update Draggable Dialog Headers 

- src/components/Steps/VStep.tsx
- src/components/Steps/VSteps.test.tsx
- src/components/Steps/VSteps.tsx
- src/components/Steps/__snapshots__/VSteps.test.tsx.snap
- src/components/Steps/components/Buttons/ButtonsBar.tsx
- src/components/Steps/components/Buttons/NextButton.tsx
- src/components/Steps/components/Buttons/PreviousButton.tsx
- src/components/Steps/components/Buttons/SubmitButton.tsx
- src/components/Steps/components/Buttons/style.tsx
- src/components/Steps/components/CheckMark.tsx
- src/components/Steps/components/StepsUpperBar/StepsUpperBar.tsx
- src/components/Steps/components/StepsUpperBar/StepsUpperBarNode.tsx
- src/components/Steps/index.ts
- src/components/Steps/types.ts
- Create VSteps and VStep component
> Feat - Create Wizard Component

- src/components/Form/Validators.ts
Description:
- Fix: Change the message of 'lte' validation
Expended Time: 1 min
> fix: Change the message of 'lte' validation

- src/components/Form/Inputs/DateTimePicker.tsx
- Updated defaultValue
- Updated minTime and maxTime
> updated defaultValue in DateTimePicker component

- src/components/Form/Inputs/SelectField.tsx
Description:
- Feat: Add the maximum number of characters visible in the menu items of the select field.
Expended Time: 10min
> Feat: Add the maximum number of characters visible in the menu items of the select field.

- src/components/Form/Inputs/DateRange.tsx
- Updated the component to react to changes if the 2 ranges are null.
- Updated to trigger the both on change functions.
> Feat- Updated OnChange function from Date Range

- src/components/Form/Inputs/DateTimePicker.tsx
Description:
- Bug fixed when resetting DateTimePicker value
Expended Time: 1h
> Fix: Bug fixed when resetting DateTimePicker value.

- src/components/Form/Inputs/SelectField.tsx
- src/components/Form/Inputs/style.tsx
Description:
- Feat: Add the skill to the selection component so that the maximum width of the popover is that of the component.
Expended Time: 1h
> Feat: Add the skill to the selection component so that the maximum width of the popover is that of the component.

- src/components/Form/Inputs/SelectField.tsx
- src/components/Form/Inputs/style.tsx
Description:
- Fix: Include the max width of 350 to the select component.
Expended Time: 1min
> Fix: Include the max width of 350 to the select component.

- src/components/DragAndDropList/DragAndDropList.tsx
- src/index.tsx
- Added empty data component to Drag and drop list component
- Basic test
Time: 1h
> Feat: Add empty data to drag and drop list

- src/components/Form/Inputs/SelectField.tsx
- src/components/Form/Inputs/SelectMultipleField.tsx
- Changed behavior of the order function.
- Removed unused variable.
> Feat- Fixed error with order that also order the no selection option

- src/components/DragAndDropList/DragAndDropList.tsx
- Changed mobx-react-lite by mobx-react in DragAndDropList component
Time: 0.5h
> Feat: changed mobx-react-lite by mobx-react in DragAndDropList component

- src/components/Form/Inputs/SelectField.tsx
- src/index.tsx
Description:
- Feat: Add ability of create new element in SelectField component.
Expended time: 3h.
> Feat: Add ability of create new element in SelectField component.

- src/components/Form/Inputs/SelectField.tsx
Description:
- Feat: Add ability to add elements in the selected field component, as  long as it does not match the query.
Expended time: 1 min
> Feat: Add ability to add elements in the selected field component, as  long as it does not match the query.

- src/components/ColorPicker/index.ts
- src/components/ColorPicker/util.ts
> Feat- Added Function to change color opacity

- src/components/Form/Inputs/NumericField.tsx
- src/components/Form/Inputs/SelectField.tsx
- src/components/Form/Inputs/VNumericFieldRounded.tsx
- src/components/Form/Validators.ts
- src/index.tsx
- Updated numeric fields behavior.
> Feat- Updated Required Validator

- src/components/Form/Inputs/SelectField.tsx
- fixed a wrong validation with an or operator.
> Fixed: Fixed issue with a parenthesis

- src/components/Form/Inputs/SelectField.tsx
- src/components/Form/Inputs/SelectMultipleField.tsx
- src/components/Form/Inputs/SelectMultipleTags.tsx
- Added behavior suggested by chao to clear the active of multi selects when opening
- Added behavior to handle many rerenders and the keyboard iteration
> Fixed: Fixed issue when only the propery allow order is used

- src/components/Form/Inputs/DateRange.tsx
Description:
- Fix: Include time precision in date range.
Expended Time: 1h
> Fix: Include time precision in date range.

- src/components/Form/Inputs/TagInputField.tsx
Description:
- Feat: Include margin in VTagInputField.
Expended Time: 1min
> Feat: Include margin in VTagInputField.

- src/components/Form/Inputs/VNumericFieldRounded.tsx
- Added support for a single 0 if the desired value is a whole number.
- updated regex to allow negative whole numbers, currently just allow negative no whole numbers.
> Feat: Added variable for no fill with zero the values.

- src/components/SelectItems/SelectUnselectItems.tsx
- src/components/SelectionList/__snapshots__/SelectionList.test.tsx.snap
Added new optional prop onReturnAssignedUnassignedItems and changed to optional handleSave and
handleSave props
> feat: updated SelectUnselectItems component

- src/components/Form/Inputs/SearchSelect/SearchSelect.tsx
- src/components/Form/Inputs/SearchSelect/SearchSelectItems.tsx
Description:
- The ability has been added in the component to select multiple so that when you have a single item selected, it displays its label.
Expended Time: 2h.
> fix(search_select): add the ability to display the label when selecting an item

- src/components/Form/Inputs/SearchSelect/SearchSelect.tsx
- src/components/Form/Inputs/SearchSelect/SearchSelectItems.tsx
> Revert "fix(search_select): add the ability to display the label when selecting an item"

- src/components/Form/Inputs/SearchSelect/SearchSelect.tsx
- src/components/Form/Inputs/SearchSelect/SearchSelectItems.tsx
Description:
- feat(search-select): add the ability to display the label when selecting an item.
> feat(search-select): add the ability to display the label when selecting an item.

- .gitignore
- src/components/Form/Inputs/CustomDateRange/CustomDateTimePicker.tsx
- src/components/Form/Inputs/CustomDateRange/components/DateRangeComponents.tsx
- src/components/Form/Inputs/CustomDateRange/components/DateRangeDateTimeSection.tsx
- src/components/Form/Inputs/CustomDateRange/components/DateRangeInput.tsx
- src/components/Form/Inputs/CustomDateRange/components/DateRangeInputSection.tsx
- src/components/Form/Inputs/CustomDateRange/components/DateRangeTimeSection.tsx
- src/components/Form/Inputs/CustomDateRange/index.ts
- src/components/Form/Inputs/CustomDateRange/styled/styles.tsx
- src/components/Form/Inputs/CustomDateRange/type/ICustomDateTimePicker.ts
- src/components/Form/Inputs/CustomDateRange/type/IDateRange.ts
- src/components/Form/Inputs/CustomDateRange/type/IDateRangeDateTimeSection.ts
- src/components/Form/Inputs/CustomDateRange/type/IDateRangeInput.ts
- src/components/Form/Inputs/CustomDateRange/type/IDateRangeInputSection.ts
- src/components/Form/Inputs/CustomDateRange/type/IDateRangeTimeSection.ts
- src/components/Form/Inputs/CustomDateRange/type/IStateCustomDateRange.ts
- src/components/Form/Inputs/CustomDateRange/type/ITransformState.ts
- src/components/Form/Inputs/CustomDateRange/type/ITypes.ts
- src/components/Form/Inputs/CustomDateRange/utils/DateRangeUtils.ts
- src/components/Form/Inputs/InputField.tsx
- src/components/Form/index.ts
- src/docs/TestSelect.tsx
Description:
feat(custom_date-range): add custom date range component
Expended time: 6h
> feat(custom_date-range): add custom date range component.

- src/components/Form/Inputs/CustomDateRange/CustomDateTimePicker.tsx
- src/components/Form/Inputs/CustomDateRange/components/DateRangeComponents.tsx
- src/components/Form/Inputs/CustomDateRange/components/DateRangeInput.tsx
- src/components/Form/Inputs/CustomDateRange/styled/styles.tsx
- src/components/Form/Inputs/CustomDateRange/type/ICustomDateTimePicker.ts
- src/components/Form/Inputs/CustomDateRange/type/IDateRange.ts
- src/components/Form/Inputs/CustomDateRange/utils/DateRangeUtils.ts
Description:
fix(custom-range-components): include validation on the  custom date range Component.
> fix(custom-range-components): include validation on the  custom date range Component.

- src/components/Form/Inputs/CustomDateRange/CustomDateTimePicker.tsx
- src/components/Form/Inputs/CustomDateRange/components/DateRangeComponents.tsx
- src/components/Form/Inputs/CustomDateRange/components/DateRangeInputSection.tsx
- src/components/Form/Inputs/CustomDateRange/type/IDateRange.ts
- src/components/Form/Inputs/CustomDateRange/type/IDateRangeInputSection.ts
Description:
- feat(custom-date-range): include the interaction with times in custom date range component.
> feat(custom-date-range): include the interaction with times in custom date range component.

- src/components/Form/Inputs/CustomDateRange/CustomDateTimePicker.tsx
- src/components/Form/Inputs/CustomDateRange/components/DateRangeComponents.tsx
- src/components/Form/Inputs/CustomDateRange/styled/styles.tsx
Optimize the interaction with the custom date range and improve the style of the same.
> fix(custom-date-range): Optimize the interaction with the custom date range and improve the style of the same.

- src/components/Form/Inputs/CustomDateRange/CustomDateTimePicker.tsx
- src/components/Form/Inputs/CustomDateRange/components/DateRangeComponents.tsx
- src/components/Form/Inputs/CustomDateRange/type/ICustomDateTimePicker.ts
- src/components/Form/Inputs/CustomDateRange/type/IDateRange.ts
Description:
- fix(custom-date-range): incluye onCloseSelectorDate prop in VCustomDateRange.
> fix(custom-date-range): incluye onCloseSelectorDate prop in VCustomDateRange.

- src/components/Form/Inputs/CustomDateRange/components/DateRangeDateTimeSection.tsx
- src/components/Form/Inputs/CustomDateRange/styled/styles.tsx
Description:
- feat(custom-date-range): add disabled prop in VCustomDateRange
> feat(custom-date-range): add disabled prop in VCustomDateRange

- src/components/Form/Inputs/CustomDateRange/components/DateRangeComponents.tsx
- src/components/Form/Inputs/CustomDateRange/components/DateRangeInputSection.tsx
- src/components/Form/Inputs/CustomDateRange/type/IDateRangeInput.ts
- src/components/Form/Inputs/CustomDateRange/type/IDateRangeInputSection.ts
- src/components/Form/Inputs/IFieldProps.tsx
- src/components/Form/Inputs/InputField.tsx
Description:
- fix(custom-date-range): add the ability for the custom date range to open the popover by clicking on the input.
> fix(custom-date-range): add the ability for the custom date range to open the popover by clicking on the input.

- src/components/Form/Inputs/CustomDateRange/CustomDateTimePicker.tsx
- src/components/Form/Inputs/CustomDateRange/components/DateRangeComponents.tsx
- src/components/Form/Inputs/CustomDateRange/components/DateRangeInputSection.tsx
- src/components/Form/Inputs/CustomDateRange/type/ICustomDateTimePicker.ts
- src/components/Form/Inputs/CustomDateRange/type/IDateRange.ts
- src/components/Form/Inputs/CustomDateRange/type/IDateRangeInputSection.ts
Description:
fix(custom-date-range): optimize custom date range component
Expended time: 2h
> fix(custom-date-range): optimize custom date range component

- src/components/Form/Inputs/TagInputField.tsx
> Revert "feat(VTagsInput): Updated VTagsInput"

- src/components/Form/Inputs/CustomDateRange/CustomDateTimePicker.tsx
- src/components/Form/Inputs/CustomDateRange/components/DateRangeComponents.tsx
- src/components/Form/Inputs/SelectMultipleTags.tsx
Description:
- fix(daterange-multipletags): changes to the CustomDaterange and VSelectMultipleTags Components.
> fix(daterange-multipletags): changes to the CustomDaterange and VSelectMultipleTags Components.

- src/components/Form/Inputs/CustomDateRange/CustomDateTimePicker.tsx
- src/components/Form/Inputs/CustomDateRange/components/DateRangeComponents.tsx
- src/components/Form/Inputs/CustomDateRange/type/IDateRange.ts
Description:
- fix(custom-date-range): shortcut problem solved
> fix(custom-date-range): shortcut problem solved

- src/components/Form/Inputs/CustomDateRange/components/DateRangeInputSection.tsx
- src/components/Form/Inputs/CustomDateRange/type/IDateRangeInput.ts
- src/components/Form/Inputs/SearchSelect/SearchSelectItems.tsx
-fix behavior with seleted items when more that one is selected
> fix(searchselectitems): fix behavior with seleted items

- src/components/Form/Inputs/CustomDateRange/components/DateRangeComponents.tsx
fix(custom-date-range): reset time when selecting user-defined shortcut
> fix(custom-date-range): reset time when selecting user-defined shortcut

- src/components/Form/Inputs/CustomDateRange/CustomDateTimePicker.tsx
- src/components/Form/Inputs/CustomDateRange/components/DateRangeComponents.tsx
- src/components/Form/Inputs/CustomDateRange/components/DateRangeDateTimeSection.tsx
- src/components/Form/Inputs/CustomDateRange/type/ICustomDateTimePicker.ts
- src/components/Form/Inputs/CustomDateRange/type/IDateRange.ts
- src/components/Form/Inputs/CustomDateRange/type/IDateRangeDateTimeSection.ts
Description:
- feat(custom-date-range): include allowSingleDayRange props in Custom Date Range component.
> feat(custom-date-range): include allowSingleDayRange props in Custom Date Range component.

- src/components/Form/Inputs/VInputWIthSuggestions.tsx
> Revert "feat updated VInputFieldWithSugestion"

- src/components/Form/Inputs/CustomDateRange/CustomDateTimePicker.tsx
- src/components/Form/Inputs/CustomDateRange/components/DateRangeComponents.tsx
- src/components/Form/Inputs/CustomDateRange/components/DateRangeDateTimeSection.tsx
- src/components/Form/Inputs/CustomDateRange/components/DateRangeInputSection.tsx
- src/components/Form/Inputs/CustomDateRange/type/ICustomDateTimePicker.ts
- src/components/Form/Inputs/CustomDateRange/type/IDateRange.ts
- src/components/Form/Inputs/CustomDateRange/type/IDateRangeDateTimeSection.ts
- src/components/Form/Inputs/CustomDateRange/type/IDateRangeInput.ts
- src/components/Form/Inputs/CustomDateRange/type/IDateRangeInputSection.ts
Description:
- fix(custom-date-range): update performance on custom date range.
> fix(custom-date-range): update performance on custom date range.

- src/components/Form/Inputs/VInputWIthSuggestions.tsx
- Added support for convert to upper case the comprovation value
> feat updated VInputFieldWithSugestion

- src/components/Form/Inputs/VInputWIthSuggestions.tsx
> Revert "refactor(autocomplete): added support for upperCase"

- src/components/Form/Inputs/VInputWIthSuggestions.tsx
> fix(autocomplete): updated check with the select to ignore case

- src/components/Form/Inputs/VInputWIthSuggestions.tsx
> feat(input with suggestion): added support tu search ignoring case

- src/components/Form/Inputs/CustomDateRange/type/ITypes.ts
- src/components/Form/Inputs/CustomDateRange/utils/DateRangeUtils.ts
Description:
- fix(custom-date-range): solved problem with custom date range in firefox browser.
> fix(custom-date-range): solved problem with custom date range in firefox browser.

- src/components/Form/Inputs/SearchSelect/SearchSelect.tsx
- src/components/Form/Inputs/SearchSelect/SearchSelectField.tsx
Description:
- fix(search_input_select): add ability to loading and remove value when Empty is allowed
> fix(search_input_select): add ability to loading and remove value when Empty is allowed

- src/components/Form/Inputs/SearchSelect/SearchSelect.tsx
Description:
- fix(i1767): multiple selection component is not working properly
> fix(i1767): multiple selection component is not working properly

- src/components/Form/Inputs/SelectMultipleTags.tsx
Added Option to trigger the onChange function when clear the vtagmultiplefield
> fix(vmultipletags): added onChange to clear button

- src/components/Form/Inputs/SearchSelect/SearchSelect.tsx
Description:
- fix(search_select): solved last one selected is not showing up right SearchSelect.
> fix(search_select): solved last one selected is not showing up right SearchSelect.

- src/components/Form/Inputs/SearchSelect/SearchSelect.tsx
- src/components/Form/Inputs/SearchSelect/SearchSelectField.tsx
Description:
- feat(placeholder): add placeholder property in VSearchSelect
> feat(placeholder): add placeholder property in VSearchSelect

- debug.log
- src/components/Form/Inputs/TagInputField.tsx
Added valdiation to avoid add just space or comma
> feat(vtaginput): added validation to empty value to avoid crazy stuffs

- src/components/Scroll/CarouselMultiple/style.tsx
- Deleted unused interface
- Changed transform on over action
> fix(scroll carousel): changed transform on hover action

- src/components/Form/Inputs/SearchSelect/SearchSelect.tsx
Fixed the user cant search for an item after other
> fix(searchselect): fixed issue when search in search Select

- package.json
Updated dependencies to fix detected issues and improve user experience
> feat(blueprint lib): updated Blueprint.js dependencies

- package.json
> Revert "feat(blueprint lib): updated Blueprint.js dependencies"

- package.json
- src/components/Form/Inputs/SelectMultipleTags.tsx
Updated BlueprintJS to avoid detected errors and improve user experience.
> feat(blueprintjs): updated BlueprintJS dependencies

- src/components/Form/Inputs/SelectMultipleTags.tsx
> Revert "feat: update Multi Select Tags Code"

- src/components/Form/Inputs/__snapshots__/InputField.test.tsx.snap
- src/components/Scroll/__snapshots__/VCarousel.test.tsx.snap
- src/components/Steps/__snapshots__/VSteps.test.tsx.snap
> Revert "fix(updated test): updated component tests"

- package.json
- src/components/Form/Inputs/SelectMultipleTags.tsx
> Revert "feat(blueprintjs): updated BlueprintJS dependencies"

- package.json
- src/components/Form/Inputs/SelectMultipleTags.tsx
- src/components/Form/Inputs/__snapshots__/InputField.test.tsx.snap
- src/components/Scroll/__snapshots__/VCarousel.test.tsx.snap
- src/components/Steps/__snapshots__/VSteps.test.tsx.snap
Updated BlueprintJS for fix the notifications issue and improve user experience
> fix(blueprint dep): updated BlueprintJS Dependency to avoid crashs

- src/components/Card/VCardPanel.tsx
- src/components/Card/types.ts
- src/components/Dialog/VDraggableModal/DraggableModal.tsx
> feat(vcard): changed VCard to be a functional component

- src/components/Form/Inputs/DateTimePicker.tsx
LINK:https://sprints.zoho.com/team/vertrax#itemdetails/P16/I3611
> feat(wx-i3611): added default false to DATETIME components

- src/components/Form/Inputs/SearchSelect/SearchSelect.tsx
- src/components/Form/Inputs/SearchSelect/SearchSelectItems.tsx
> fix(serach-select): cannot select items in a dropdown by clicking on the checkbox.

- package.json
- src/components/Form/Inputs/DateTimePicker.tsx
- src/components/Form/Inputs/SelectField.tsx
removed usePortal variable by default in the selects and datePickers
> fix(vselectfield): fixed issue with select

- src/components/Form/Inputs/SelectField.tsx
> fix(wx-i3922): problem creating new item in SelectField when matching  text

- src/components/Dialog/VDraggableModal/DraggableModalInner.tsx
- src/components/Dialog/VDraggableModal/dialog.tsx
- src/components/Dialog/VDraggableModal/draggableModalReducer.ts
Changes in the way modals is showed in small screens. (top and left)
> Changes in draggableModals for correct display in small screens
